# Generated by Django 2.2.14 on 2020-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201211_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='productId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contemporary',
            name='productId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cubism',
            name='productId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='impressionism',
            name='productId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modern',
            name='productId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='surrealism',
            name='productId',
            field=models.IntegerField(null=True),
        ),
    ]
