# Generated by Django 2.2.14 on 2020-12-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201211_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='contemporary',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='cubism',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='impressionism',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='modern',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='surrealism',
            name='productId',
        ),
    ]
