# Generated by Django 2.2.14 on 2020-12-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201211_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productId',
        ),
    ]
