# Generated by Django 2.2.14 on 2020-12-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201215_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
