# Generated by Django 2.2.14 on 2020-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201216_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
