# Generated by Django 2.2.14 on 2020-12-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
    ]
