# Generated by Django 2.2.14 on 2020-12-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubism',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
